
services:
  database:
    container_name: 'postgresDb'
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=guest'
      - 'POSTGRES_DB=ledgerDb'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      -  "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=secret"

  prometheus:
    image: prom/prometheus:v2.44.0
    network_mode: bridge
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

#  grafana:
#    image: grafana/grafana:9.5.2
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    restart: unless-stopped
#    volumes:
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
