scrape_configs:
  - job_name: 'Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['<machine.ip>:8080']
        labels:
          application: 'LedgerApplication'